baseurl = "http://baardkrk.github.io/"
languageCode = "en-us"
title = "Bard's notes"
theme = "m10c"
paginate = 5

[params]
  author = "Bård-Kristian Krohg"
  description = "Just a developer with developing interests all over the place"
  avatar = "/img/profile_pic.jpeg"

  [[params.social]]
    name = "github"
    url = "https://github.com/baardkrk"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/baardkrk"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/kigbit"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/kigbit"

  [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"
  
